const data=[
    {
      "date": "2021-12-31",
      "product": "Cricket Bats",
      "investment": 12121,
      "sales": 17151.1,
      "revenue": 2237.1
    },
    {
      "date": "2021-12-31",
      "product": "Cricket Bats",
      "investment": 8452,
      "sales": 10226.92,
      "revenue": 1774.92
    },
    {
      "date": "2023-12-31",
      "product": "Cricket Bats",
      "investment": 6114,
      "sales": 7275.66,
      "revenue": 1161.66
    },
    {
      "date": "2021-12-31",
      "product": "Cricket Balls",
      "investment": 14617,
      "sales": 17686.57,
      "revenue": 3069.57
    },
    {
      "date": "2022-12-31",
      "product": "Cricket Balls",
      "investment": 15029,
      "sales": 15479.87,
      "revenue": 450.87
    },
    {
      "date": "2023-12-31",
      "product": "Cricket Balls",
      "investment": 13131,
      "sales": 15231.96,
      "revenue": 2100.96
    },
    {
      "date": "2021-12-31",
      "product": "Cricket Gloves",
      "investment": 16614,
      "sales": 19272.24,
      "revenue": 2658.24
    },
    {
      "date": "2022-12-31",
      "product": "Cricket Gloves",
      "investment": 861,
      "sales": 1076.25,
      "revenue": 215.25
    },
    {
      "date": "2023-12-31",
      "product": "Cricket Gloves",
      "investment": 16818,
      "sales": 17490.72,
      "revenue": 672.72
    },
    {
      "date": "2021-12-31",
      "product": "Cricket Helmet",
      "investment": 12688,
      "sales": 14210.56,
      "revenue": 1522
    },
    {
      "date": "2022-12-31",
      "product": "Cricket Helmet",
      "investment": 6837,
      "sales": 7725.81,
      "revenue": 888.81
    },
    {
      "date": "2023-12-31",
      "product": "Cricket Helmet",
      "investment": 5520,
      "sales": 5685.6,
      "revenue": 165.6
    },
    {
      "date": "2021-12-31",
      "product": "Cricket stumps",
      "investment": 1027,
      "sales": 1252.94,
      "revenue": 225.94
    },
    {
      "date": "2022-12-31",
      "product": "Cricket stumps",
      "investment": 10512,
      "sales": 10827.36,
      "revenue": 315.36
    },
    {
      "date": "2023-12-31",
      "product": "Cricket stumps",
      "investment": 2485,
      "sales": 2957.15,
      "revenue": 472.15
    },
    {
      "date": "2021-12-31",
      "product": "Dressing Kit",
      "investment": 1990,
      "sales": 2407.9,
      "revenue": 417.9
    },
    {
      "date": "2022-12-31",
      "product": "Dressing Kit",
      "investment": 8034,
      "sales": 9399.78,
      "revenue": 1365.78
    },
    {
      "date": "2023-12-31",
      "product": "Dressing Kit",
      "investment": 13254,
      "sales": 14314.32,
      "revenue": 1060.32
    },
    {
      "date": "2021-12-31",
      "product": "Paper Towels",
      "investment": 18545,
      "sales": 21141.3,
      "revenue": 2596.3
    },
    {
      "date": "2022-12-31",
      "product": "Paper Towels",
      "investment": 6168,
      "sales": 7524.96,
      "revenue": 1356.96
    },
    {
      "date": "2023-12-31",
      "product": "Paper Towels",
      "investment": 12382,
      "sales": 14610.76,
      "revenue": 2228.76
    },
    {
      "date": "2021-12-31",
      "product": "Cricket pads",
      "investment": 12498,
      "sales": 14622.66,
      "revenue": 2124.66,
      "revenueper": 17
    },
    {
      "date": "2022-12-31",
      "product": "Cricket pads",
      "investment": 8214,
      "sales": 8953.26,
      "revenue": 739.26
    },
    {
      "date": "2023-12-31",
      "product": "Cricket pads",
      "investment": 3361,
      "sales": 3865.15,
      "revenue": 504.15
    },
    {
      "date": "2021-12-31",
      "product": "Cricket shoes",
      "investment": 16152,
      "sales": 18413.28,
      "revenue": 2261.28
    },
    {
      "date": "2022-12-31",
      "product": "Cricket shoes",
      "investment": 2303,
      "sales": 2349.06,
      "revenue": 46.06
    },
    {
      "date": "2023-12-31",
      "product": "Product I",
      "investment": 14806,
      "sales": 18063.32,
      "revenue": 3257.32
    }
  ];